domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

title: IBCalvários
description: Repositório de documentação da Igreja Batista do Calvário de Santo André