title: IBCalvário
description: Repositório de documentação da Igreja Batista do Calvário de Santo André
url: https://ibcalvario.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""      # place folder name if the site is served in a subfolder
domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-feed

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme